### PR TITLE
Add skipping light updates option

### PR DESCRIPTION
**Pull request by devalnor**
New feature: 
- Option to skip light updates. 

It solve request https://github.com/Foddy/node-red-contrib-huemagic/issues/107

Regards,
Mx

### CODE REVIEW

**Comment by Foddy** [comment]
Sorry... Unfortunately, this was not the right place that causes API limit errors, which is why I had to revoke it. The requests to the bridge take place in the "recheck" method under "hue-bridge-config.js".

But I added a small delay between requests to the Hue Bridge (in v2.0.5). Maybe this solves your problem? :S

**Comment by devalnor** [comment]
When enabled, this feature just disable the `bridge.events.on(...)` function like the "universal mode". The idea behind is that we don't want to recieve auto or delayed updates from the light but only on demand from an input flow like `inject`. 
I don't get the API limit errors except if we spam the manual update.

**Comment by Foddy** [comment]
Hm I understand. Please give me some time so I can implement the whole thing a little more "elegantly". It would be optimal if this setting also means that the requests on the bridge no longer take place and that the setting can also be used for groups and other nodes.

I will come back to this soon!

**Comment by Foddy** [comment]
Should be available in v2.1 :)!

**Comment by devalnor** [comment]
Hi @Foddy,

Thanks for you update, I tested in 2.2.2 but unfortunately it does not have the expected behaviour. 
We don't receive any update from an input flow when "Skip events from node" is set to true.

My fault, I think that we did not work on the same feature.
On my side "Skip events from node" means doing nothing when light change but it may work only on demand.

Here an example of flow who require this feature:
image

In this flow, the blink alert will loop infinitly and this is why the "Skip events from node" is required for.

I hope my explanation is better this time.

**Comment by townsmcp** [comment]
Should 'Skip events' option also work for Hue motion sensor? I have been testing a flow but when selecting inject node (or in the proper flow using a stoptimer node) no payload passes through/queries the state of the hue motion sensor. See attached pic of a simple test flow that - even when hooking a debug node on the output of the motion sensor there is no output
Skip events

**Comment by Foddy** [comment]
The motion sensor only accepts a boolean command to activate or deactivate the device. If you deactivate the sensor you will not receive any events at all, regardless of how the "Skip events" option is set.

I would suggest to combine the motion sensor with a the default function node and either check if the motion occurred at a specific time or store the current state in context: https://nodered.org/docs/user-guide/context

After that you could query your context variable if the last state was an “active” state and continue with your flow. It may sound a bit complicated, but it isn’t 😉.

**Comment by townsmcp** [comment]
Thanks @Foddy. I’ve done that in other flows for variables, lol just thought there might have been an easier way to have less nodes on a flow because the option was there in motion node 👍

**Pull request merged**
